/**
 * Antecedentes / Base Legal del informe de implementación del ENEIS: texto
 * legal fijo (Constitución, LOEI, Reglamento, Acuerdo Ministerial y Modelo
 * de Gestión DECE), igual en cualquier institución del país. Se transcribe
 * tal cual del formato oficial para que el DECE no tenga que volver a
 * escribirlo o copiarlo cada vez que genera un informe.
 */
export interface LegalParagraph {
  heading?: boolean;
  text: string;
}

export const ENEIS_BASE_LEGAL: LegalParagraph[] = [
  { heading: true, text: "BASE LEGAL.-" },
  { heading: true, text: "CONSTITUCIÓN DE LA REPÚBLICA DEL ECUADOR:" },
  { text: 'Art. 26.- "La educación es un derecho de las personas a lo largo de su vida y un deber ineludible e inexcusable del Estado. Constituye un área prioritaria de la política pública y de la inversión estatal, garantía de la igualdad e inclusión social y condición indispensable para el buen vivir. Las personas, las familias y la sociedad tienen el derecho y la responsabilidad de participar en el proceso educativo".' },
  { text: 'Art. 27.- "La educación se centrará en el ser humano y garantizará su desarrollo holístico, en el marco del respeto a los derechos humanos, al medio ambiente sustentable y a la democracia; será participativa, obligatoria, intercultural, democrática, incluyente y diversa, de calidad y calidez; impulsará la equidad de género, la justicia, la solidaridad y la paz; estimulará el sentido crítico, el arte y la cultura física, la iniciativa individual y comunitaria, y el desarrollo de competencias y capacidades para crear y trabajar. La educación es indispensable para el conocimiento, el ejercicio de los derechos y la construcción de un país soberano, y constituye un eje estratégico para el desarrollo nacional".' },
  { text: 'Art. 44.- "El Estado, la sociedad y la familia promoverán de forma prioritaria el desarrollo integral de las niñas, niños y adolescentes, y asegurarán el ejercicio pleno de sus derechos; se atenderá al principio de su interés superior y sus derechos prevalecerán sobre los de las demás personas".' },
  { heading: true, text: "LEY ORGÁNICA DE EDUCACIÓN INTERCULTURAL:" },
  { text: 'Art. 4.- Principios rectores de la educación.- "(…) a. Acceso universal a la educación: Se garantiza el acceso universal, integrador y equitativo a una educación de calidad; la permanencia, movilidad y culminación del ciclo de enseñanza de calidad para niñas, niños, adolescentes y jóvenes, promoviendo oportunidades de aprendizaje para todas y todos a lo largo de la vida sin ningún tipo de discriminación y exclusión; b. No discriminación: Se prohíbe la discriminación, exclusión, restricción, preferencia u otro trato diferente que directa o indirectamente se base en los motivos prohibidos de discriminación y que tenga por objeto o por resultado anular o menoscabar el reconocimiento, goce o ejercicio de los derechos reconocidos en la Constitución, los instrumentos de derechos humanos y la presente Ley; c. Igualdad de oportunidades y de trato: Se garantizan entornos de aprendizaje accesibles y asequibles material y económicamente a todas las niñas, niños y adolescentes, respetando sus diversas necesidades, capacidades y características, eliminando todas las formas de discriminación. Se establecerán medidas de acción afirmativa para efectivizar el ejercicio del derecho a la educación".' },
  { text: 'Art. 5.- Principios de aplicación de la Ley.- "(…) a. Interés superior de los niños, niñas y adolescentes: El interés superior de niños, niñas y adolescentes es un derecho sustantivo, un principio de interpretación y una norma de procedimiento. Debe ser aplicado por las instituciones estatales, las autoridades educativas, docentes, servidoras, servidores, empleadas y empleados, instituciones educativas públicas, fiscomisionales, municipales y particulares y cualquier otra modalidad educativa. La aplicación de este, debe contar con la escucha efectiva de la opinión de niños, niñas y adolescentes; la valoración de la situación concreta y las particularidades individuales que inciden en el ejercicio pleno de sus derechos, así como la consideración de los contextos, situaciones y necesidades particulares de un determinado niño, niña o adolescente o grupo de niños, niñas o adolescentes. b. Interculturalidad y plurinacionalidad: La interculturalidad y plurinacionalidad garantizan el reconocimiento, respeto y recreación de las expresiones culturales de las diferentes nacionalidades, culturas y pueblos que conforman el Ecuador; así como sus saberes ancestrales, promoviendo la unidad en la diversidad, el diálogo intercultural y reconoce el derecho de todas las personas, comunas, comunidades, pueblos y nacionalidades a acceder a los servicios presenciales o virtuales y obras de la biblioteca escolar que se encuentre en su propia lengua y en los idiomas oficiales de relación intercultural; c. Equidad: La equidad asegura a todas las personas el acceso, permanencia, aprendizaje, participación, promoción y culminación en el Sistema Educativo. Garantiza la igualdad de oportunidades a comunidades, pueblos, nacionalidades, grupos de atención prioritaria, en situación de vulnerabilidad, mediante medidas de acción afirmativa fomentando una cultura escolar incluyente, erradicando toda forma de discriminación, generando políticas y aplicando prácticas educativas inclusivas; d. Inclusión: La inclusión reconoce la diversidad de las personas, los pueblos y nacionalidades, a las diferencias individuales y colectivas como una oportunidad para el enriquecimiento de la sociedad, a través de la activa participación e interacción en las dimensiones familiar, social, educativa, laboral, en general en todos los procesos sociales, culturales y en las comunidades; Adicionalmente, se promoverá y garantizará a toda persona, comunidades, pueblos, nacionalidades y grupos con necesidades educativas específicas el acceso de manera permanente a los servicios presenciales o virtuales de las bibliotecas escolares y a los materiales y herramientas pedagógicas que garanticen su efectiva inclusión; e. Igualdad de género: La educación debe garantizar la igualdad de condiciones, oportunidades y trato entre hombres y mujeres promoviendo una educación libre de violencias; (…)".' },
  { text: 'Art. 8.- Enfoques.- "(…) a. Derechos Humanos: Este enfoque pone como centro al ser humano, tanto en su dimensión individual como social. La educación es un derecho que permite desarrollar otros tipos de derechos para alcanzar una vida digna; b. Primera Infancia, Niñez y Adolescencia: El enfoque de derechos de la niñez y la adolescencia obliga a que las necesidades y los derechos, así como la opinión y la participación de ellos estén en el centro de todas las actividades financieras, administrativas, pedagógicas, curriculares y extracurriculares, así como las políticas públicas que establezcan las distintas instancias o sujetos de la comunidad educativa en el ámbito de sus competencias, contemplando su interés superior; c. Género: Considera las diferentes oportunidades que tienen los hombres y las mujeres, sin discriminación por razones de orientación sexual o identidad de género, las interrelaciones existentes entre ellos y los distintos papeles que socialmente se les asignan. Las relaciones de género desiguales derivan de los modos en que las culturas asignan las funciones y responsabilidades distintas a la mujer y al hombre. Ello a la vez determina diversas formas de acceder a los recursos materiales o no materiales (…)".' },
  { text: 'Art. 13.- Obligaciones del Estado.- "(…) El Estado tiene las siguientes obligaciones adicionales: a. Garantizar, bajo los principios de equidad, igualdad, no discriminación y libertad, que todas las personas tengan acceso a la educación pública de calidad y cercanía; b. Asegurar que los establecimientos educativos sean espacios democráticos de ejercicio de derechos y convivencia pacífica; f. Garantizar que todas las entidades educativas desarrollen una educación integral, coeducativa, con una visión transversal y enfoque de derechos; i. Erradicar todas las formas de violencia en el sistema educativo y velar por la integridad física, psicológica y sexual de la comunidad educativa, con particular énfasis en los estudiantes; x. Garantizar una educación para la democracia, sustentada en derechos obligaciones y responsabilidades; en principios y valores, orientada a profundizar la democracia participativa de los miembros de la comunidad educativa; y. Garantizar una educación integral que incluya la educación en sexualidad, humanística, científica como legítimo derecho al buen vivir; (…)".' },
  { text: 'Art. 14.- Derechos.- "Los estudiantes tienen los siguientes derechos: a. Ser actores fundamentales en el proceso educativo; c. Ser tratado con justicia, dignidad, sin discriminación, con respeto a su diversidad individual, cultural, sexual y lingüística, a sus convicciones ideológicas, políticas y religiosas, y a sus derechos y libertades fundamentales garantizados en la Constitución de la República, tratados e instrumentos internacionales y la Ley; h. Ser protegidos contra todo tipo de violencia en los establecimientos educativos, así como a denunciar ante las autoridades e instituciones competentes cualquier violación a sus derechos fundamentales o garantías constitucionales, cualquier acción u omisión que atente contra la dignidad e integridad física, sicológica o sexual de la persona; a ejercer su derecho a la protección; (…)".' },
  { text: 'Art. 72.- Departamento de Consejería Estudiantil.- "El Departamento de Consejería Estudiantil es un organismo técnico, especializado, inter y multidisciplinario de las instituciones educativas encargado de implementar la atención y velar por el desarrollo integral de los estudiantes, con la participación y apoyo de la comunidad educativa; especialmente el acompañamiento de padres y madres de familia, sustentado en el interés superior del niño como principio, derecho y regla de procedimiento, así como los principios de corresponsabilidad y debida diligencia; y bajo el enfoque de derechos, inclusión, género, intergeneracional, interculturalidad, movilidad, interseccionalidad y plurinacionalidad en garantía de los derechos colectivos de los pueblos y nacionalidades. El proyecto de vida integral definido en esta Ley y en concordancia con todos los estándares que progresivamente desarrolle este concepto será una herramienta que los Departamentos de Consejería Estudiantil observarán para la ejecución de sus funciones".' },
  { text: 'Art. 73.- Atribuciones del Departamento de Consejería Estudiantil.- "(…) a. Asesorar a la institución educativa en la implementación de estrategias para contribuir en la construcción de relaciones pacíficas y armónicas, en el marco de una cultura de paz y no violencia, garantizando una amplia participación de la comunidad educativa. b. Promover en común con la comunidad educativa, espacios dignos, participativos y seguros; así como el desarrollo y la implementación participativa de los planes y programas de prevención de los factores de riesgo individual, psicosocial, comunitario y en emergencias naturales y antrópicas. c. Asesorar a la comunidad educativa para establecer acciones participativas de prevención de vulneraciones y promoción de derechos, así como la detección, intervención, derivación, referencia y contra referencia, y seguimiento de casos provenientes de situaciones de riesgo psicosocial, violencia, exclusión o vulneración de derechos de los niños, niñas y adolescentes, en el marco de los protocolos dispuestos por las autoridades rectoras: para cuyo efecto se establecerán hojas de ruta con los organismos del Sistema de Protección Integral de Derechos de Niñas, Niños y Adolescentes, Sistema Integral para Prevenir y Erradicar la Violencia Contra las Mujeres, Sistema de Inclusión Económica y Social, Sistema de Salud, otros sistemas de protección, instancias administrativas, la Defensoría del Pueblo y órganos especializados de la administración de justicia (…)".' },
  { text: 'Art. 113.- Definición de cultura de paz y convivencia armónica.- "Se entiende por cultura de paz y convivencia armónica al conjunto de valores, actitudes, tradiciones, prácticas sociales, comportamientos que se basan en el respeto a los derechos humanos, la diversidad, la solidaridad, el compromiso del arreglo pacífico de los conflictos; permitiendo la construcción de una sociedad justa, equitativa, participativa en el marco del cumplimiento de los fines y objetivos del Sistema Nacional de Educación".' },
  { text: 'Art. 118.- De la prevención de la violencia en el contexto educativo.- "El Estado garantizará el desarrollo trasversal del enfoque de derechos humanos y de género en la construcción de los currículos nacionales; definirá la estrategia nacional de educación integral de la sexualidad, establecerá de manera prioritaria y transversal en el Sistema Nacional de Educación políticas públicas que incorporen lineamientos que garanticen el diseño de acciones, instrumentos y mecanismos dirigidos a la disminución de riesgo de ocurrencia de casos de violencia en la comunidad educativa, a través de la capacitación, formación y sensibilización de docentes, estudiantes y padres de familia; inclusión de mecanismos de prevención en los Códigos de Convivencia que desarrollen una cultura de protección y autoprotección de los miembros de la comunidad educativa; y el fortalecimiento de capacidades institucionales, entre otros. La Autoridad Nacional de Educación en coordinación con la Defensoría del Pueblo, los Consejos Nacionales para la Igualdad y los Consejos Cantonales de Protección de Derechos desarrollarán los mecanismos de seguimiento, evaluación y recomendaciones a la política pública que tenga como objetivo prevenir la violencia en el contexto educativo".' },
  { text: 'Art. 120.- Plan Nacional para la Erradicación de la Violencia en el Contexto Educativo.- "La Autoridad Educativa Nacional en coordinación con la Defensoría del Pueblo, los Consejos de Igualdad y el ente rector de Justicia y Derechos Humanos elaborará, implementará y evaluará el Plan Nacional para la Erradicación de la Violencia en el Contexto Educativo que contendrá las políticas, estrategias, programas, proyectos, acciones y mecanismos concretos para la prevención, detección y atención de toda forma de violencia en el contexto educativo, así como la protección y reparación de derechos de las víctimas; incluirá mecanismos de coordinación con otras instituciones del Estado en el ámbito de sus competencias; definirá los comportamientos violentos que se intentan prevenir y atender; analizará las causas primarias de esta conducta; identificar los grupos sociales en riesgo; formulará sistemas o mecanismos de prevención y atención de la violencia escolar a través del uso de recursos cognitivos, emocionales y sociales; incorporará investigación estadística; evaluará y medirá los resultados de las intervenciones".' },
  { text: 'DISPOSICIONES GENERALES. DÉCIMA TERCERA.- "La Autoridad Educativa Nacional incorporará de forma obligatoria en el currículo la educación integral en sexualidad, entendiendo la misma como algo inherente al ser humano, con enfoque de derechos y desde una perspectiva bio-psico-social, con sustento científico. Superando las visiones sesgadas, subjetivas y dogmáticas. La misma que deberá adaptar sus contenidos a todos los niveles desde el inicial hasta el bachillerato en todos los establecimientos educativos públicos, privados y fiscomisionales".' },
  { heading: true, text: "REGLAMENTO A LA LEY ORGÁNICA DE EDUCACIÓN INTERCULTURAL." },
  { heading: true, text: "CAPÍTULO XI — DEPARTAMENTOS DE CONSEJERÍA ESTUDIANTIL" },
  { text: 'Artículo 282.- Funciones.- "Será responsabilidad de los profesionales de la educación que integran los Departamentos de Consejería Estudiantil, lo siguiente: Dar cumplimiento a las atribuciones establecidas en la Ley Orgánica de Educación Intercultural; (…) Acompañar, orientar y brindar asesoramiento a toda la comunidad educativa para articular acciones conjuntas que promuevan el desarrollo y bienestar integral de la población estudiantil para fortalecer el proceso de enseñanza aprendizaje en el ejercicio pleno de sus derechos; Generar acciones y estrategias orientadas a toda la comunidad educativa para el ejercicio pleno de los derechos humanos y hábitos de vida saludable para el fortalecimiento del desarrollo integral del estudiantado; Asesorar a docentes y familiares sobre las diferentes problemáticas o situaciones de riesgo que pueden presentarse a lo largo del proceso educativo desde una perspectiva etaria, fomentando de esta forma buenas prácticas educativas y la corresponsabilidad en el bienestar del estudiante, bajo los enfoques de inclusión y de derechos; Asesorar, participar y contribuir en el proceso de acompañamiento socioemocional en la institución educativa; Implementar estrategias participativas en la comunidad educativa para la prevención de vulneración de derechos y prevención de riesgos psicosociales enfocados al desarrollo de factores protectores en el ámbito educativo y familiar; Implementar acciones que fortalezcan la capacidad de respuesta inmediata y oportuna de las instituciones educativas frente a situaciones de vulneración o violencia detectadas o cometidas en el sistema educativo; Acompañar en el desarrollo de las acciones para atender a las necesidades de estudiantes que han sido víctimas de cualquier tipo de vulneración de derechos en el marco de la protección integral que contemple la detección, intervención, derivación y seguimiento; Generar y articular, con el resto de los miembros de la comunidad educativa acciones que permitan que las y los estudiantes que se encuentran en una situación de vulnerabilidad o riesgo, reciban atención integral para reestablecer su estado de bienestar y su (re)integración a la institución educativa, en garantía de su integridad física y emocional favoreciendo a su permanencia, continuidad y culminación de su proceso educativo; (…) n. Otras funciones establecidas en la Ley Orgánica de Educación Intercultural y este Reglamento". La Autoridad Educativa Nacional determinará las responsabilidades específicas para los roles de los profesionales del DECE, sobre la base de las atribuciones establecidas en la Ley Orgánica de Educación Intercultural y las funciones establecidas en este Reglamento.' },
  { text: 'Artículo 329.- Estrategia Nacional de Educación Integral de la Sexualidad.- "La Autoridad Educativa Nacional, contando con la participación de estudiantes y familias, formulará la política pública que garantice el efectivo acceso al derecho a educación integral de la sexualidad".' },
  { heading: true, text: "ACUERDO Nro. MINEDUC-MINEDUC-2023-00065-A" },
  { text: 'Art. 1.- Expedir la "Estrategia Nacional de Educación Integral en Sexualidad", documento que se adjunta como anexo al presente Instrumento y constituye parte integral del mismo.' },
  { text: 'Art. 2.- La "Estrategia Nacional de Educación Integral en Sexualidad" será de aplicación obligatoria para todas las instituciones educativas de los sostenimientos fiscal, fiscomisional, municipal y particular, a nivel nacional.' },
  { heading: true, text: "MODELO DE GESTIÓN DECE:" },
  { heading: true, text: "Eje de Consejería" },
  { text: '"La consejería es la acción de acompañar, orientar y brindar asesoramiento a toda la comunidad educativa con el objetivo de articular las acciones para la consolidación de la convivencia armónica y la construcción de proyectos de vida integrales de la población estudiantil". El eje de consejería dirigirá las siguientes acciones:' },
  { text: 'AEC 1. "Ejecución de estrategias para que las y los estudiantes realicen un proceso de introspección y empoderamiento sobre sus derechos que les permita tomar decisiones con respecto a la construcción de sus proyectos de vida integrales, de manera consciente, corresponsable, libre y autónoma (…)".' },
  { text: 'AEC 3. "Orientación a docentes, personal educativo, autoridades educativas, familias, tutores pedagógicos de las diferentes ofertas y modalidades del sistema educativo para garantizar el bienestar socioemocional de la población estudiantil y la consolidación de la convivencia armónica".' },
  { heading: true, text: "Eje de Promoción y Prevención" },
  { text: '"Son las acciones orientadas a generar las condiciones para que la población estudiantil ejerza plenamente sus derechos e identifique problemáticas psicosociales que afecten su desarrollo integral. La promoción es el proceso informativo y sensibilizador que permite conocer la importancia del respeto, ejercicio, exigibilidad y garantía de los derechos humanos. La prevención es la identificación de los potenciales factores de riesgos psicosociales a los cuales la población estudiantil puede estar expuesta y la identificación de los factores de protección para potenciarlos. Las acciones de promoción y prevención deben enmarcarse en las especificidades de los diferentes grupos que conforman la población estudiantil en el sistema educativo nacional. El eje de promoción y prevención dirigirá las siguientes acciones: (…) AEPP3. Desarrollo de espacios de sensibilización, diálogo, capacitación y asesoramiento para la comunidad educativa, enfocados en prevenir riesgos psicosociales, prácticas discriminatorias y excluyentes a lo largo del proceso educativo, con enfoque de pertinencia territorial y desde la construcción de los escenarios para el ejercicio pleno de los derechos humanos (…)".' },
  { heading: true, text: "Eje de Atención Psicosocial" },
  { text: '"Son las acciones para la detección, intervención, derivación, seguimiento y reparación, dirigidas a estudiantes que se encuentren atravesando por situaciones como: inestabilidad emocional, conflictos (individual, escolar, familiar, social, adaptativo), desastre natural, vulneración de derechos, o de riesgo psicosocial que pueda afectar su desarrollo integral. En este contexto, el Departamento de Consejería es clave en la dinámica institucional de manera que, oportunamente, pueda identificar, con el apoyo de los demás profesionales de la educación, situaciones que no contribuyan al desarrollo integral de la población estudiantil y se constituyan en riesgos psicosociales".' },
  { heading: true, text: "Gestión de los Departamentos de Consejería Estudiantil — Principios y enfoques" },
  { text: 'Atención Integral.- "Por la cual la persona es atendida de manera indivisible en el marco de sus condiciones individuales, familiares y sociales, sus circunstancias socio-culturales, género, edad, origen y otras condiciones específicas, desde una perspectiva inter y multidisciplinaria".' },
  { text: 'Igualdad de género.- "La educación debe garantizar la igualdad de condiciones, oportunidades y trato entre hombres y mujeres promoviendo una educación libre de violencias".' },
  { text: 'Interés superior de los niños, niñas y adolescentes.- "Debe ser aplicado por las instituciones estatales, las autoridades educativas, docentes, servidoras, servidores, empleadas y empleados, instituciones educativas públicas, fiscomisionales, municipales y particulares y cualquier otra modalidad educativa. La aplicación de este, debe contar con la escucha efectiva de la opinión de niños, niñas y adolescentes; la valoración de la situación concreta y las particularidades individuales que inciden en el ejercicio pleno de sus derechos, así como la consideración de los contextos, situaciones y necesidades particulares de un determinado niño, niña o adolescente o grupo de niños, niñas o adolescentes".' },
  { text: "En tal razón se levanta el presente informe con la finalidad de recopilar la información requerida en base a la Implementación de la Estrategia Nacional de Educación Integral en Sexualidad “ENEIS” para los fines pertinentes." },
];

/** Objetivo fijo del informe (mismo texto en cualquier institución). */
export const ENEIS_INFORME_OBJETIVO =
  'Informar sobre las actividades realizadas en la aplicación de la Estrategia Nacional de Educación Integral en Sexualidad "ENEIS" a nivel institucional fortaleciendo las acciones y precautelando el bienestar de los niños, niñas y adolescentes en el contexto educativo.';
