import type { SquareDefinition, BackupQuestion, FunFact, TeamColor, EjeType } from "./types";

export const OFFICIAL_CREDIT =
  "Contenido original: Guía Parchís Inclusivo, programa Respiramos Inclusión — World Vision Ecuador y ACNUR, Quito, abril 2021. Elaborado por Jhon Tenesaca, Lourdes Lema, Paulina Alcázar y Washington Saltos. Colaboración: Ismenia Íñiguez Romero. Esta es una adaptación interactiva no oficial para uso en talleres.";

export const EJES_INFO: Record<
  EjeType,
  { name: string; color: TeamColor; colorHex: string; description: string; icon: string }
> = {
  IDENTIDAD: {
    name: "Identidad",
    color: "AMARILLO",
    colorHex: "#EAB308", // Yellow-500
    description: "Reconocer las múltiples identidades que nos conforman.",
    icon: "🪞",
  },
  DIVERSIDAD: {
    name: "Diversidad",
    color: "VERDE",
    colorHex: "#10B981", // Emerald-500
    description: "Valorar y disfrutar las diferencias de la comunidad educativa.",
    icon: "🌱",
  },
  JUSTICIA: {
    name: "Justicia",
    color: "VIOLETA",
    colorHex: "#8B5CF6", // Purple-500
    description: "Reconocer y velar por la justicia y la igualdad social.",
    icon: "⚖️",
  },
  CAMBIO_SOCIAL: {
    name: "Cambio Social",
    color: "AZUL",
    colorHex: "#0284C7", // Sky-600
    description: "Empoderar para generar cambios individuales y colectivos.",
    icon: "🌊",
  },
};

export const SQUARES_CATALOG: SquareDefinition[] = [
  // ==========================================
  // ZONA AMARILLA — IDENTIDAD (Casilleros 5 a 21)
  // ==========================================
  {
    number: 5,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "BIENVENIDA",
    tag: "[Bienvenida]",
    title: "Bienvenida al Camino Inclusivo",
    text: "Felicitaciones, iniciaste un camino inclusivo para tu espacio educativo seguro. Menciona el nombre de tu equipo y canta tu barra.",
    isInclusiveZone: true,
  },
  {
    number: 6,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Identidad",
    text: "¿Qué características crees que conforman tu identidad?",
    isInclusiveZone: false,
  },
  {
    number: 7,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Identidad",
    text: "¿Qué características te hacen único o diferente a los demás?",
    isInclusiveZone: false,
  },
  {
    number: 8,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Identidad",
    text: "Menciona 4 elementos que forman parte de tu identidad social. ¿Sientes que puedes expresarte con libertad y sentirte feliz por ello?",
    isInclusiveZone: false,
  },
  {
    number: 9,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Identidad",
    text: "¿Por qué es importante valorar la identidad de otras personas?",
    isInclusiveZone: false,
  },
  {
    number: 10,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "RETROCEDE_INICIO",
    tag: "[Retrocede al inicio]",
    title: "Prejuicio",
    text: "Un estudiante sufrió bullying por parte de sus compañeros en el momento que expresó su homosexualidad. Regresa al inicio del camino para ayudar a rectificar esta acción con tus compañeros.",
    isInclusiveZone: false,
    returnToStart: true,
  },
  {
    number: 11,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "DATO_CURIOSO",
    tag: "[Dato curioso]",
    title: "Dato curioso sobre movilidad",
    text: "¿Sabías que las personas migrantes venezolanas caminan cerca de 21 días para llegar a la frontera ecuatoriana? ¿Qué opinas al respecto?",
    isInclusiveZone: false,
  },
  {
    number: 12,
    zone: "AMARILLO",
    eje: "IDENTIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Identidad en plenitud",
    text: "Reconocemos nuestra identidad y la vivimos en plenitud. ¿Qué crees que haría falta para que las y los estudiantes puedan expresar su identidad con libertad?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 13,
    zone: "AMARILLO",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Diversidad",
    text: "¿Cuándo fue la primera vez que notaste un trato diferente hacia otras personas? (Nacionalidad, etnia, color de piel, sexo, género).",
    isInclusiveZone: false,
  },
  {
    number: 14,
    zone: "AMARILLO",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Diversidad en medios",
    text: "¿Qué mensajes discriminatorios ves en los medios de comunicación? (Sexo, grupos étnicos, religión, región, nacionalidad).",
    isInclusiveZone: false,
  },
  {
    number: 15,
    zone: "AMARILLO",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Diversidad e igualdad",
    text: "¿Crees que las mujeres tienen las mismas oportunidades que los hombres? Explica tu respuesta.",
    isInclusiveZone: false,
  },
  {
    number: 16,
    zone: "AMARILLO",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Voz de la niñez y adolescencia",
    text: "¿Consideras que la opinión de niños, niñas y adolescentes es tomada en cuenta igual que la de las personas adultas?",
    isInclusiveZone: false,
  },
  {
    number: 17,
    zone: "AMARILLO",
    eje: "DIVERSIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Valoramos la diversidad",
    text: "Valoramos la diversidad que conforma nuestra comunidad. ¿Crees que un hombre puede estudiar una carrera de belleza?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 18,
    zone: "AMARILLO",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Justicia",
    text: "¿Qué es para ti la justicia y cómo crees que podemos hacerla respetar?",
    isInclusiveZone: false,
  },
  {
    number: 19,
    zone: "AMARILLO",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Micro-agresiones",
    text: "¿Has sido testigo de una micro-agresión? Cuéntanos qué sucedió.",
    isInclusiveZone: false,
  },
  {
    number: 20,
    zone: "AMARILLO",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Movilidad humana y educación",
    text: "¿Por qué consideras importante que los niños, niñas y adolescentes en movilidad humana estén dentro del sistema educativo?",
    isInclusiveZone: false,
  },
  {
    number: 21,
    zone: "AMARILLO",
    eje: "JUSTICIA",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Justicia e igualdad social",
    text: "Reconoce y vela por la justicia y la igualdad social. Niñas, niños, adolescentes y docentes comprendieron que los apodos son una forma de discriminación, y ya no los utilizan.",
    isInclusiveZone: true,
    advanceBonus: 2,
  },

  // ==========================================
  // ZONA VERDE — DIVERSIDAD (Casilleros 22 a 38)
  // ==========================================
  {
    number: 22,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "BIENVENIDA",
    tag: "[Bienvenida]",
    title: "Bienvenida al Camino Inclusivo",
    text: "Felicitaciones, iniciaste un camino inclusivo para tu espacio educativo seguro. Menciona el nombre de tu equipo y canta tu barra.",
    isInclusiveZone: true,
  },
  {
    number: 23,
    zone: "VERDE",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Inclusión y discapacidad",
    text: "¿Crees que niñas y niños con algún tipo de discapacidad deben y pueden acudir a una institución educativa regular?",
    isInclusiveZone: false,
  },
  {
    number: 24,
    zone: "VERDE",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Mitos sobre la adolescencia",
    text: "¿Qué opinas de la frase «los adolescentes están en la edad del burro»?",
    isInclusiveZone: false,
  },
  {
    number: 25,
    zone: "VERDE",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Estereotipos de género",
    text: "¿Qué pensamientos te vienen cuando miras a un hombre vestido de mujer?",
    isInclusiveZone: false,
  },
  {
    number: 26,
    zone: "VERDE",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Nacionalidades en la educación",
    text: "¿Qué opinas si en tu escuela o colegio contratan profesionales de otras nacionalidades?",
    isInclusiveZone: false,
  },
  {
    number: 27,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "RETROCEDE_INICIO",
    tag: "[Retrocede al inicio]",
    title: "Micro-agresión y prejuicio",
    text: "En un bus, al subir un grupo de personas afroecuatorianas, la mayoría de pasajeros guardó sus pertenencias, lo cual demuestra un prejuicio. Regresa al inicio del camino para ayudar a cambiar esta actitud.",
    isInclusiveZone: false,
    returnToStart: true,
  },
  {
    number: 28,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "DATO_CURIOSO",
    tag: "[Dato curioso]",
    title: "Dato curioso sobre migración",
    text: "¿Sabías que el 20% de la población ecuatoriana ha migrado a otros países?",
    isInclusiveZone: false,
  },
  {
    number: 29,
    zone: "VERDE",
    eje: "IDENTIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Privilegio y desventaja",
    text: "Reconocemos nuestra identidad y la vivimos en plenitud. ¿Crees que hay identidades que son privilegiadas y otras que están en desventaja?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 30,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Sentido de la inclusión",
    text: "¿La inclusión significa que las personas que \"no son como yo\" deben aprender a pensar y actuar como yo?",
    isInclusiveZone: false,
  },
  {
    number: 31,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Etiquetas escolares",
    text: "¿Cómo afectan las etiquetas en tu institución educativa y en el aula de clase?",
    isInclusiveZone: false,
  },
  {
    number: 32,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Frases discriminatorias",
    text: "¿Qué piensas al escuchar «parece merienda de negros»?",
    isInclusiveZone: false,
  },
  {
    number: 33,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "ACTIVIDAD",
    tag: "[Actividad grupal]",
    title: "La historia de mis zapatos",
    text: "Cada participante responde: ¿A dónde fueron con los zapatos que traen puestos? ¿Qué situaciones difíciles vivieron con ellos? ¿Si tuvieran que salir del país, a dónde querrían ir con esos zapatos?",
    isInclusiveZone: false,
  },
  {
    number: 34,
    zone: "VERDE",
    eje: "DIVERSIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Valoramos la diversidad",
    text: "Valoramos la diversidad que conforma nuestra comunidad. Menciona las diversidades que reconoces en tu institución educativa.",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 35,
    zone: "VERDE",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Roles y protección",
    text: "¿Consideras que los niños deben proteger a las niñas?",
    isInclusiveZone: false,
  },
  {
    number: 36,
    zone: "VERDE",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Corresponsabilidad en el hogar",
    text: "¿Quién debe preparar la comida, papá o mamá?",
    isInclusiveZone: false,
  },
  {
    number: 37,
    zone: "VERDE",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Autonomía y género",
    text: "¿Qué opinas acerca de que las mujeres viajen solas?",
    isInclusiveZone: false,
  },
  {
    number: 38,
    zone: "VERDE",
    eje: "JUSTICIA",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Actuar ante la violencia",
    text: "Reconoce y vela por la justicia y la igualdad social. ¿Qué harías si ves a un compañero o compañera llegar a tu institución con signos de violencia?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },

  // ==========================================
  // ZONA VIOLETA — JUSTICIA (Casilleros 39 a 55)
  // ==========================================
  {
    number: 39,
    zone: "VIOLETA",
    eje: "JUSTICIA",
    type: "BIENVENIDA",
    tag: "[Bienvenida]",
    title: "Bienvenida al Camino Inclusivo",
    text: "Felicitaciones, iniciaste un camino inclusivo para tu espacio educativo seguro. Menciona el nombre de tu equipo y canta tu barra.",
    isInclusiveZone: true,
  },
  {
    number: 40,
    zone: "VIOLETA",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Hospitalidad y migración",
    text: "¿Estás de acuerdo con que vengan personas de otros países a vivir en Ecuador?",
    isInclusiveZone: false,
  },
  {
    number: 41,
    zone: "VIOLETA",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Empatía internacional",
    text: "Si tuvieras que vivir en otro país, ¿cómo quisieras que te traten?",
    isInclusiveZone: false,
  },
  {
    number: 42,
    zone: "VIOLETA",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Origen y valoración",
    text: "Si pudieses decidir nacer en otro país, ¿cuál escogerías? ¿Por qué?",
    isInclusiveZone: false,
  },
  {
    number: 43,
    zone: "VIOLETA",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Orgullo y singularidad",
    text: "En 2 minutos, nombra 3 características que hacen de tu país un lugar único.",
    isInclusiveZone: false,
  },
  {
    number: 44,
    zone: "VIOLETA",
    eje: "JUSTICIA",
    type: "RETROCEDE_INICIO",
    tag: "[Retrocede al inicio]",
    title: "Discriminación institucionalizada",
    text: "A un compañero no le dejaron ingresar a la institución porque llegó con el cabello pintado. Regresa al inicio para crear un círculo restaurativo que resuelva esta situación.",
    isInclusiveZone: false,
    returnToStart: true,
  },
  {
    number: 45,
    zone: "VIOLETA",
    eje: "JUSTICIA",
    type: "DATO_CURIOSO",
    tag: "[Dato curioso]",
    title: "Dato histórico sobre migraciones",
    text: "Entre 1824 y 1924, 59 millones de europeos salieron de sus países hacia América; más del 70% fue a América del Norte y el 21% optó por América Latina.",
    isInclusiveZone: false,
  },
  {
    number: 46,
    zone: "VIOLETA",
    eje: "IDENTIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Identidad en plenitud",
    text: "Reconocemos nuestra identidad y la vivimos en plenitud. ¿Consideras que es chévere vivir en plenitud tu identidad?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 47,
    zone: "VIOLETA",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Convivencia y diferencias",
    text: "¿La inclusión significa que las personas que \"no son como yo\" deben aprender a pensar y actuar como yo? ¿Qué opinas?",
    isInclusiveZone: false,
  },
  {
    number: 48,
    zone: "VIOLETA",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Aprendizaje de actitudes",
    text: "¿Cómo adquieres y aprendes las actitudes, valores y creencias que te permiten interactuar con otras personas?",
    isInclusiveZone: false,
  },
  {
    number: 49,
    zone: "VIOLETA",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Igualdad de derechos",
    text: "¿Crees que las personas de distintos países en movilidad deben tener los mismos derechos y obligaciones que las personas ecuatorianas?",
    isInclusiveZone: false,
  },
  {
    number: 50,
    zone: "VIOLETA",
    eje: "DIVERSIDAD",
    type: "ACTIVIDAD",
    tag: "[Actividad grupal]",
    title: "Barra sobre la diversidad",
    text: "Hagan una barra con su equipo sobre la diversidad.",
    isInclusiveZone: false,
  },
  {
    number: 51,
    zone: "VIOLETA",
    eje: "DIVERSIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Apreciar las diferencias",
    text: "Valoramos la diversidad que conforma nuestra comunidad. ¿Es importante entender y apreciar tus diferencias, y las de otras personas, para convivir en diversidad?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 52,
    zone: "VIOLETA",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Espacios sin discriminación",
    text: "¿Qué se necesita para propiciar espacios libres de discriminación en tu institución educativa?",
    isInclusiveZone: false,
  },
  {
    number: 53,
    zone: "VIOLETA",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Propuestas de inclusión",
    text: "¿Qué propones para que tu institución educativa sea más inclusiva?",
    isInclusiveZone: false,
  },
  {
    number: 54,
    zone: "VIOLETA",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Impacto del lenguaje violento",
    text: "¿De qué manera afecta a un estudiante que le digan vago, tonto o bruto? (Micro-agresiones).",
    isInclusiveZone: false,
  },
  {
    number: 55,
    zone: "VIOLETA",
    eje: "JUSTICIA",
    type: "ESPECIAL_AVANCE",
    tag: "[Avanza 2 si responde; si no conoce, no avanza]",
    title: "Tipos de discriminación",
    text: "Reconoce y vela por la justicia y la igualdad social. Indica al menos 2 tipos de discriminación que conoces.",
    isInclusiveZone: false,
    advanceBonus: 2,
  },

  // ==========================================
  // ZONA AZUL — CAMBIO SOCIAL (Casilleros 56 a 68, y 1 a 4)
  // ==========================================
  {
    number: 56,
    zone: "AZUL",
    eje: "CAMBIO_SOCIAL",
    type: "BIENVENIDA",
    tag: "[Bienvenida]",
    title: "Bienvenida al Camino Inclusivo",
    text: "Felicitaciones, iniciaste un camino inclusivo para tu espacio educativo seguro. Menciona el nombre de tu equipo y canta tu barra.",
    isInclusiveZone: true,
  },
  {
    number: 57,
    zone: "AZUL",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Único e irrepetible",
    text: "¿Qué características consideras que te hacen único e irrepetible?",
    isInclusiveZone: false,
  },
  {
    number: 58,
    zone: "AZUL",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Inteligencia y etnia",
    text: "¿Consideras que la inteligencia de una persona depende de su etnia o nacionalidad? Explica tu respuesta.",
    isInclusiveZone: false,
  },
  {
    number: 59,
    zone: "AZUL",
    eje: "IDENTIDAD",
    type: "ACTIVIDAD",
    tag: "[Actividad]",
    title: "Expresión de identidades",
    text: "Demuestra cómo expresas tus identidades — por ejemplo, cantando, bailando o dibujando.",
    isInclusiveZone: false,
  },
  {
    number: 60,
    zone: "AZUL",
    eje: "IDENTIDAD",
    type: "NORMAL",
    title: "Construcción de la identidad",
    text: "¿Cómo crees que se forma tu identidad?",
    isInclusiveZone: false,
  },
  {
    number: 61,
    zone: "AZUL",
    eje: "JUSTICIA",
    type: "RETROCEDE_INICIO",
    tag: "[Retrocede al inicio]",
    title: "Exclusión sistémica",
    text: "El código de convivencia establece que las niñas embarazadas no pueden ser admitidas en la institución educativa. Regresa al inicio del camino para reflexionar e incidir sobre esta decisión.",
    isInclusiveZone: false,
    returnToStart: true,
  },
  {
    number: 62,
    zone: "AZUL",
    eje: "JUSTICIA",
    type: "DATO_CURIOSO",
    tag: "[Dato curioso, avanza 2]",
    title: "Mujeres en la ciencia",
    text: "Muchas mujeres aportaron a la ciencia — Marie Curie fundó la ciencia de la radioactividad, y gracias a su descubrimiento se encontraron curas efectivas para el cáncer.",
    isInclusiveZone: false,
    advanceBonus: 2,
  },
  {
    number: 63,
    zone: "AZUL",
    eje: "IDENTIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Libertad de identidad",
    text: "Reconocemos nuestra identidad y la vivimos en plenitud. ¿Qué elementos conforman tu identidad? ¿Sientes que la puedes expresar con libertad?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 64,
    zone: "AZUL",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Discriminación y justicia",
    text: "¿Crees que una sociedad que discrimina es una sociedad justa? Explica tu respuesta.",
    isInclusiveZone: false,
  },
  {
    number: 65,
    zone: "AZUL",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Prejuicios institucionales",
    text: "Identifica y nombra los prejuicios que ves en tu institución educativa. ¿Cómo podrías contrarrestarlos?",
    isInclusiveZone: false,
  },
  {
    number: 66,
    zone: "AZUL",
    eje: "DIVERSIDAD",
    type: "NORMAL",
    title: "Protección estatal a personas en movilidad",
    text: "¿Consideras que las personas refugiadas o migrantes deben ser protegidas por el Estado?",
    isInclusiveZone: false,
  },
  {
    number: 67,
    zone: "AZUL",
    eje: "CAMBIO_SOCIAL",
    type: "ACTIVIDAD",
    tag: "[Actividad]",
    title: "Acróstico de inclusión",
    text: "Formen un acróstico con la palabra INCLUSIÓN.",
    isInclusiveZone: false,
  },
  {
    number: 68,
    zone: "AZUL",
    eje: "DIVERSIDAD",
    type: "ZONA_INCLUSIVA",
    tag: "[Zona inclusiva, avanza 2]",
    title: "Diversidad para la inclusión",
    text: "Valoramos la diversidad que conforma nuestra comunidad. ¿Cómo ayuda la diversidad a la inclusión?",
    isInclusiveZone: true,
    advanceBonus: 2,
  },
  {
    number: 1,
    zone: "AZUL",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Compromiso contra la discriminación",
    text: "¿Qué práctica discriminatoria identificada en tu institución te comprometerías a reducir o eliminar? ¿De qué manera?",
    isInclusiveZone: false,
  },
  {
    number: 2,
    zone: "AZUL",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Ejes visibles de inclusión",
    text: "¿Qué eje de la inclusión crees que es más evidente en tu institución educativa?",
    isInclusiveZone: false,
  },
  {
    number: 3,
    zone: "AZUL",
    eje: "JUSTICIA",
    type: "NORMAL",
    title: "Conciencia de micro-agresiones",
    text: "¿Crees que a veces no somos conscientes de las micro-agresiones que cometemos y recibimos?",
    isInclusiveZone: false,
  },
  {
    number: 4,
    zone: "AZUL",
    eje: "JUSTICIA",
    type: "ESPECIAL_AVANCE",
    tag: "[Avanza 2 si responde con reflexión; si solo se ríe, no avanza]",
    title: "Chistes machistas y reflexión",
    text: 'Reconoce y vela por la justicia y la igualdad social. "¿Qué hace una mujer fuera de la cocina? Turismo." ¿Qué piensas sobre este chiste?',
    isInclusiveZone: false,
    advanceBonus: 2,
  },
];

export const BACKUP_QUESTIONS: BackupQuestion[] = [
  {
    letter: "A",
    text: "¿Qué prácticas debes cambiar en la institución educativa para que se respeten los derechos de todos y todas, y no exista discriminación?",
  },
  {
    letter: "B",
    text: "¿Qué propones para mejorar las políticas de la institución educativa, para que sean más inclusivas? (Códigos de convivencia, normativas).",
  },
  {
    letter: "C",
    text: "¿Cómo es para ti una institución educativa que respira inclusión?",
  },
  {
    letter: "D",
    text: "¿Qué cambio quieres ver en el personal docente y autoridades para que haya inclusión?",
  },
  {
    letter: "E",
    text: "¿Cómo crees que debe ser la enseñanza en el aula para que todas y todos participen con motivación?",
  },
  {
    letter: "F",
    text: "¿Qué acciones y prácticas son inaceptables en tu institución educativa?",
  },
  {
    letter: "G",
    text: "¿Cuáles son las fortalezas con las que aportas para generar inclusión en tu familia, comunidad y contexto educativo?",
  },
  {
    letter: "H",
    text: "Si te enteras de que hay personas que hacen bullying, ¿qué harías para reducirlo o eliminarlo?",
  },
  {
    letter: "I",
    text: "Si eres parte del Consejo Estudiantil, ¿qué acciones ejecutarías para que sea una institución inclusiva?",
  },
  {
    letter: "J",
    text: "¿Qué debes hacer cuando observas una práctica discriminatoria?",
  },
  {
    letter: "K",
    text: "¿Crees que en las familias se puede practicar la inclusión?",
  },
];

export const FUN_FACTS: FunFact[] = [
  {
    id: 1,
    text: "La Constitución del Ecuador protege a niños, niñas y adolescentes de cualquier situación de violencia. ¿Crees que se cumple este mandato?",
  },
  {
    id: 2,
    text: "En Ecuador hay 14 nacionalidades indígenas.",
  },
  {
    id: 3,
    text: "Existen países que aún castigan con pena de muerte el amor entre personas del mismo sexo, como Irán, Mauritania, Sudán y Nigeria.",
  },
  {
    id: 4,
    text: "El 1 de marzo se celebra el Día para la Cero Discriminación.",
  },
];

/** Búsqueda rápida de casillero por número (1 a 68) */
export function getSquareByNumber(num: number): SquareDefinition | undefined {
  return SQUARES_CATALOG.find((sq) => sq.number === num);
}
